AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  SAM template con Cognito (login/registro) y DynamoDB (almacenamiento de usuarios).
  Usa una Lambda PostConfirmation en Python 3.12.

Globals:
  Function:
    Timeout: 10
    Runtime: python3.12

Resources:

  UsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-Users"
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  # --------------------------------------- [SINGLE TABLE DESIGN CHATBOT] ---------------------------------------

  PetsChatbotTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub "${AWS::StackName}-chatdata"
      AttributeDefinitions:
        - AttributeName: PK # Partition Key
          AttributeType: S
        - AttributeName: SK # Sort Key
          AttributeType: S
      KeySchema:
        - AttributeName: PK 
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST


  # --------------------------------------- [COGNITO USER POOL + CLIENTE] ---------------------------------------

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${AWS::StackName}-UserPool"
      AutoVerifiedAttributes:
        - email
      UsernameAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
          RequireUppercase: true
      MfaConfiguration: "OFF"
      Schema:
        - Name: email
          Required: true
          Mutable: true
      LambdaConfig:
        PostConfirmation: !GetAtt PostConfirmationFunction.Arn

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "${AWS::StackName}-UserPoolClient"
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
      PreventUserExistenceErrors: ENABLED
      AccessTokenValidity: 1
      IdTokenValidity: 1
      RefreshTokenValidity: 30

  CognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub "${AWS::StackName}-auth-domain"
      UserPoolId: !Ref CognitoUserPool

  # --------------------------------------- [IDENTITY POOL - PARA CREDENCIALES AWS TEMPORALES] ---------------------------------------

  CognitoIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: !Sub "${AWS::StackName}-IdentityPool"
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId: !Ref CognitoUserPoolClient
          ProviderName: !GetAtt CognitoUserPool.ProviderName

  CognitoIdentityPoolAuthRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-CognitoAuthRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                cognito-identity.amazonaws.com:aud: !Ref CognitoIdentityPool
              "ForAnyValue:StringLike":
                cognito-identity.amazonaws.com:amr: authenticated
      Policies:
        - PolicyName: CognitoAuthorizedPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                Resource:
                  - !GetAtt UsersTable.Arn
                  - !GetAtt PetsChatbotTable.Arn


  CognitoIdentityPoolRoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref CognitoIdentityPool
      Roles:
        authenticated: !GetAtt CognitoIdentityPoolAuthRole.Arn

  # --------------------------------------- [LAMBDA POST CONFIRMATION] ---------------------------------------

  PostConfirmationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-PostConfirmation"
      Description: "Post confirmation trigger - guarda usuarios en DynamoDB tras registro"
      CodeUri: backend/post_confirmation/
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 10
      MemorySize: 128
      Environment:
        Variables:
          USERS_TABLE: !Ref UsersTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref UsersTable

  AllowCognitoInvokePostConfirmation:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref PostConfirmationFunction
      Action: lambda:InvokeFunction
      Principal: cognito-idp.amazonaws.com
      SourceArn: !GetAtt CognitoUserPool.Arn

Outputs:
  UserPoolId:
    Description: "ID del User Pool"
    Value: !Ref CognitoUserPool
  UserPoolClientId:
    Description: "Client ID del User Pool"
    Value: !Ref CognitoUserPoolClient
  IdentityPoolId:
    Description: "ID del Identity Pool"
    Value: !Ref CognitoIdentityPool
  UsersTableName:
    Description: "Nombre de la tabla DynamoDB de usuarios"
    Value: !Ref UsersTable
  PostConfirmationFunctionName:
    Description: "Lambda PostConfirmation"
    Value: !Ref PostConfirmationFunction
  ChatTableName:
    Description: "Tabla DynamoDB para chats y mensajes"
    Value: !Ref PetsChatbotTable

